import * as Local from '@getflywheel/local';
import * as LocalMain from '@getflywheel/local/main';
import { execFile } from 'child_process';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);

/**
 * The IPC channel the "Trust" button in Local's SSL tab sends to. Local's own
 * X509CertService handles it with @vscode/sudo-prompt, which on modern macOS
 * silently fails to apply the trust settings (the cert lands in the keychain
 * but SecTrustSettings are never written). Running the exact same command in
 * an interactive Terminal works, so this add-on takes over the channel and
 * does exactly that.
 */
const TRUST_CHANNEL = 'trustSiteCert';

const SCRIPT_NAME = 'trust-ssl.sh';
const SYSTEM_KEYCHAIN = '/Library/Keychains/System.keychain';

// Local registers its own trustSiteCert listener during boot; poll until it
// exists (or give up) before replacing it, so we never end up with both.
const TAKEOVER_POLL_MS = 500;
const TAKEOVER_TIMEOUT_MS = 30000;

// After opening Terminal, poll the System keychain until the user has
// authenticated and the cert shows up as trusted.
const TRUST_POLL_MS = 3000;
const TRUST_TIMEOUT_MS = 5 * 60 * 1000;

const buildTrustScript = (domain: string, certPath: string): string => `#!/bin/bash
#
# ${SCRIPT_NAME} — generated by the "Trust SSL — macOS Fix" Local add-on.
# Trusts the Local SSL certificate for ${domain} in the macOS System keychain.
# Safe to delete; it is re-created every time you click "Trust" in Local.

CERTFILE="${certPath}"

if [ ! -e "$CERTFILE" ]; then
	echo "❌ Could not find the certificate file to trust:"
	echo "   $CERTFILE"
	exit 1
fi

echo "Local wants to trust the SSL certificate for ${domain}:"
echo "   $CERTFILE"
echo
echo "You will be asked for your macOS administrator password (sudo)."
echo

if sudo security add-trusted-cert -d -r trustRoot -p ssl -k ${SYSTEM_KEYCHAIN} "$CERTFILE"; then
	echo
	echo "✅ Certificate trusted. Local will pick this up automatically within a few seconds."
	echo "   You can close this window."
else
	echo
	echo "❌ Trusting the certificate failed."
	exit 1
fi
`;

/**
 * SHA-256 fingerprint of the certificate's DER body, uppercase hex — the same
 * format `security find-certificate -Z` prints and that Local's own trust
 * status check matches against.
 */
const certificateFingerprint = (certPath: string): string => {
	const pem = fs.readFileSync(certPath, 'utf8');
	const match = pem.match(/-----BEGIN CERTIFICATE-----([\s\S]+?)-----END CERTIFICATE-----/);

	if (!match) {
		throw new Error(`No PEM certificate block found in ${certPath}`);
	}

	const der = Buffer.from(match[1].replace(/\s+/g, ''), 'base64');

	return crypto.createHash('sha256').update(der).digest('hex').toUpperCase();
};

const isCertificateTrusted = async (fingerprint: string): Promise<boolean> => {
	try {
		const { stdout } = await execFileAsync('security', ['find-certificate', '-a', '-Z', SYSTEM_KEYCHAIN]);

		return new RegExp(`^SHA-256 hash: ${fingerprint}`, 'im').test(stdout);
	} catch (err) {
		return false;
	}
};

export default function (context: LocalMain.AddonMainContext): void {
	const { electron } = context;

	if (process.platform !== 'darwin') {
		return;
	}

	const { localLogger, sendIPCEvent } = LocalMain.getServiceContainer().cradle;

	const logger = localLogger.child({
		thread: 'main',
		addon: 'local-trust-ssl-macos',
	});

	const sitesInFlight = new Set<string>();

	const showBanner = (siteJson: Local.SiteJSON, id: string, variant: string, title: string, message: string) => {
		sendIPCEvent('showSiteBanner', {
			siteID: siteJson.id,
			id,
			variant,
			title,
			message,
			dismissible: true,
		});
	};

	const clearBanner = (siteJson: Local.SiteJSON, id: string) => {
		sendIPCEvent('clearSiteBanner', {
			siteID: siteJson.id,
			id,
		});
	};

	const pollUntilTrusted = async (siteJson: Local.SiteJSON, fingerprint: string, scriptPath: string): Promise<void> => {
		const deadline = Date.now() + TRUST_TIMEOUT_MS;

		while (Date.now() < deadline) {
			if (await isCertificateTrusted(fingerprint)) {
				logger.info(`Certificate for ${siteJson.domain} is now trusted.`);

				clearBanner(siteJson, 'trust-ssl-macos-opened');
				sendIPCEvent('siteCertTrusted', siteJson, true);

				new electron.Notification({
					title: 'Site SSL',
					body: `The SSL certificate for ${siteJson.domain} is now trusted.`,
				}).show();

				fs.rmSync(scriptPath, { force: true });

				return;
			}

			await new Promise((resolve) => setTimeout(resolve, TRUST_POLL_MS));
		}

		logger.warn(`Timed out waiting for the certificate of ${siteJson.domain} to become trusted.`);

		clearBanner(siteJson, 'trust-ssl-macos-opened');
		showBanner(
			siteJson,
			'trust-ssl-macos-timeout',
			'warning',
			'Heads-up!',
			`The SSL certificate for ${siteJson.domain} still isn't trusted. You can run ${SCRIPT_NAME} in the site folder manually to try again.`,
		);
	};

	const trustViaTerminal = async (siteJson: Local.SiteJSON): Promise<boolean> => {
		const certPath = path.join(
			electron.app.getPath('userData'),
			'run', 'router', 'nginx', 'certs',
			`${siteJson.domain}.crt`,
		);

		if (!fs.existsSync(certPath)) {
			logger.warn(`Certificate file not found for ${siteJson.domain}: ${certPath}`);

			showBanner(
				siteJson,
				'trust-ssl-macos-no-cert',
				'warning',
				'Heads-up!',
				`Could not find the SSL certificate for ${siteJson.domain}. Start the site once, then try again.`,
			);

			return false;
		}

		if (sitesInFlight.has(siteJson.id)) {
			logger.info(`Trust already in progress for ${siteJson.domain}; ignoring click.`);

			return false;
		}

		clearBanner(siteJson, 'trust-ssl-macos-timeout');
		clearBanner(siteJson, 'trust-ssl-macos-no-cert');

		const siteRoot = LocalMain.formatHomePath(siteJson.path);
		const scriptPath = path.join(siteRoot, SCRIPT_NAME);
		const fingerprint = certificateFingerprint(certPath);

		fs.writeFileSync(scriptPath, buildTrustScript(siteJson.domain, certPath), { mode: 0o755 });
		fs.chmodSync(scriptPath, 0o755);

		logger.info(`Opening Terminal to trust the certificate for ${siteJson.domain} (${scriptPath}).`);

		await execFileAsync('open', ['-a', 'Terminal', scriptPath]);

		showBanner(
			siteJson,
			'trust-ssl-macos-opened',
			'neutral',
			'Almost there!',
			`A Terminal window was opened. Enter your macOS password there to trust the certificate for ${siteJson.domain}.`,
		);

		sitesInFlight.add(siteJson.id);

		pollUntilTrusted(siteJson, fingerprint, scriptPath).finally(() => {
			sitesInFlight.delete(siteJson.id);
		});

		return true;
	};

	const takeOverTrustChannel = () => {
		const existing = electron.ipcMain.listenerCount(TRUST_CHANNEL);

		electron.ipcMain.removeAllListeners(TRUST_CHANNEL);

		LocalMain.addIpcAsyncListener(TRUST_CHANNEL, (siteJson: Local.SiteJSON) => trustViaTerminal(siteJson));

		logger.info(`Took over the ${TRUST_CHANNEL} IPC channel (replaced ${existing} built-in listener(s)).`);
	};

	const waitStart = Date.now();

	const tryTakeOver = () => {
		if (electron.ipcMain.listenerCount(TRUST_CHANNEL) > 0) {
			takeOverTrustChannel();

			return;
		}

		if (Date.now() - waitStart > TAKEOVER_TIMEOUT_MS) {
			logger.warn(`Local never registered a ${TRUST_CHANNEL} listener; registering ours anyway.`);
			takeOverTrustChannel();

			return;
		}

		setTimeout(tryTakeOver, TAKEOVER_POLL_MS);
	};

	electron.app.whenReady().then(tryTakeOver);
}
